from django.shortcuts import render
from coint.models import Pair, Company
from django.utils.timezone import activate
from coint_site.settings import TIME_ZONE
import logging
import json
import os
from coint.pairs import get_pair

activate(TIME_ZONE)

logger = logging.getLogger(__name__)


def home(request):
    """
    Sends the visitor to the homepage

    :param request: http request object
    :return:
    """
    MIN_P_VALUE = .99
    logger.warning('home view: ' + request.META.get('REMOTE_ADDR'))
    logger.info('Fetched companies')
    pairs = sorted(Pair.objects.filter(adf_p__gt=MIN_P_VALUE), key=lambda x: x.adf_stat, reverse=True)
    pairs = pairs[:10]
    logger.info('Fetched pairs')

    nodes = {
        unicode('nodes'): [],
        unicode('links'): []
    }

    i = 1
    for p in pairs:
        s1, s2 = p.component_tickers()
        c1 = Company.objects.get(symbol=s1)
        c2 = Company.objects.get(symbol=s2)
        if c1.industry == c2.industry:
            nodes['nodes'].append({unicode('name'): p.symbol, unicode('group'): 1, unicode('id'): i, unicode('symbols'): [s1, s2], unicode('adf'): p.adf_stat})
        else:
            nodes['nodes'].append({unicode('name'): p.symbol, unicode('group'): 1, unicode('id'): i, unicode('symbols'): [s1, s2], unicode('adf'): p.adf_stat})
        i += 1
    logger.info('Made nodes.')

    links = []
    for n in nodes['nodes']:
        for s in n['symbols']:
            for m in nodes['nodes']:
                if s in m['symbols']:
                    if {n['id'], m['id']} not in links:
                        nodes['links'].append({unicode('source'): n['id'], unicode('target'): m['id'], unicode('value'): int(1 + n['adf'] * m['adf'])})
                        links.append({n['id'], m['id']})
    logger.info('Made links.')

    sample = {u'links': [{u'source': 1, u'target': 0, u'value': 1},
  {u'source': 2, u'target': 0, u'value': 8},
  {u'source': 3, u'target': 0, u'value': 10},
  {u'source': 3, u'target': 2, u'value': 6},
  {u'source': 4, u'target': 0, u'value': 1},
  {u'source': 5, u'target': 0, u'value': 1},
  {u'source': 6, u'target': 0, u'value': 1},
  {u'source': 7, u'target': 0, u'value': 1},
  {u'source': 8, u'target': 0, u'value': 2},
  {u'source': 9, u'target': 0, u'value': 1},
  {u'source': 11, u'target': 10, u'value': 1},
  {u'source': 11, u'target': 3, u'value': 3},
  {u'source': 11, u'target': 2, u'value': 3},
  {u'source': 11, u'target': 0, u'value': 5},
  {u'source': 12, u'target': 11, u'value': 1},
  {u'source': 13, u'target': 11, u'value': 1},
  {u'source': 14, u'target': 11, u'value': 1},
  {u'source': 15, u'target': 11, u'value': 1},
  {u'source': 17, u'target': 16, u'value': 4},
  {u'source': 18, u'target': 16, u'value': 4},
  {u'source': 18, u'target': 17, u'value': 4},
  {u'source': 19, u'target': 16, u'value': 4},
  {u'source': 19, u'target': 17, u'value': 4},
  {u'source': 19, u'target': 18, u'value': 4},
  {u'source': 20, u'target': 16, u'value': 3},
  {u'source': 20, u'target': 17, u'value': 3},
  {u'source': 20, u'target': 18, u'value': 3},
  {u'source': 20, u'target': 19, u'value': 4},
  {u'source': 21, u'target': 16, u'value': 3},
  {u'source': 21, u'target': 17, u'value': 3},
  {u'source': 21, u'target': 18, u'value': 3},
  {u'source': 21, u'target': 19, u'value': 3},
  {u'source': 21, u'target': 20, u'value': 5},
  {u'source': 22, u'target': 16, u'value': 3},
  {u'source': 22, u'target': 17, u'value': 3},
  {u'source': 22, u'target': 18, u'value': 3},
  {u'source': 22, u'target': 19, u'value': 3},
  {u'source': 22, u'target': 20, u'value': 4},
  {u'source': 22, u'target': 21, u'value': 4},
  {u'source': 23, u'target': 16, u'value': 3},
  {u'source': 23, u'target': 17, u'value': 3},
  {u'source': 23, u'target': 18, u'value': 3},
  {u'source': 23, u'target': 19, u'value': 3},
  {u'source': 23, u'target': 20, u'value': 4},
  {u'source': 23, u'target': 21, u'value': 4},
  {u'source': 23, u'target': 22, u'value': 4},
  {u'source': 23, u'target': 12, u'value': 2},
  {u'source': 23, u'target': 11, u'value': 9},
  {u'source': 24, u'target': 23, u'value': 2},
  {u'source': 24, u'target': 11, u'value': 7},
  {u'source': 25, u'target': 24, u'value': 13},
  {u'source': 25, u'target': 23, u'value': 1},
  {u'source': 25, u'target': 11, u'value': 12},
  {u'source': 26, u'target': 24, u'value': 4},
  {u'source': 26, u'target': 11, u'value': 31},
  {u'source': 26, u'target': 16, u'value': 1},
  {u'source': 26, u'target': 25, u'value': 1},
  {u'source': 27, u'target': 11, u'value': 17},
  {u'source': 27, u'target': 23, u'value': 5},
  {u'source': 27, u'target': 25, u'value': 5},
  {u'source': 27, u'target': 24, u'value': 1},
  {u'source': 27, u'target': 26, u'value': 1},
  {u'source': 28, u'target': 11, u'value': 8},
  {u'source': 28, u'target': 27, u'value': 1},
  {u'source': 29, u'target': 23, u'value': 1},
  {u'source': 29, u'target': 27, u'value': 1},
  {u'source': 29, u'target': 11, u'value': 2},
  {u'source': 30, u'target': 23, u'value': 1},
  {u'source': 31, u'target': 30, u'value': 2},
  {u'source': 31, u'target': 11, u'value': 3},
  {u'source': 31, u'target': 23, u'value': 2},
  {u'source': 31, u'target': 27, u'value': 1},
  {u'source': 32, u'target': 11, u'value': 1},
  {u'source': 33, u'target': 11, u'value': 2},
  {u'source': 33, u'target': 27, u'value': 1},
  {u'source': 34, u'target': 11, u'value': 3},
  {u'source': 34, u'target': 29, u'value': 2},
  {u'source': 35, u'target': 11, u'value': 3},
  {u'source': 35, u'target': 34, u'value': 3},
  {u'source': 35, u'target': 29, u'value': 2},
  {u'source': 36, u'target': 34, u'value': 2},
  {u'source': 36, u'target': 35, u'value': 2},
  {u'source': 36, u'target': 11, u'value': 2},
  {u'source': 36, u'target': 29, u'value': 1},
  {u'source': 37, u'target': 34, u'value': 2},
  {u'source': 37, u'target': 35, u'value': 2},
  {u'source': 37, u'target': 36, u'value': 2},
  {u'source': 37, u'target': 11, u'value': 2},
  {u'source': 37, u'target': 29, u'value': 1},
  {u'source': 38, u'target': 34, u'value': 2},
  {u'source': 38, u'target': 35, u'value': 2},
  {u'source': 38, u'target': 36, u'value': 2},
  {u'source': 38, u'target': 37, u'value': 2},
  {u'source': 38, u'target': 11, u'value': 2},
  {u'source': 38, u'target': 29, u'value': 1},
  {u'source': 39, u'target': 25, u'value': 1},
  {u'source': 40, u'target': 25, u'value': 1},
  {u'source': 41, u'target': 24, u'value': 2},
  {u'source': 41, u'target': 25, u'value': 3},
  {u'source': 42, u'target': 41, u'value': 2},
  {u'source': 42, u'target': 25, u'value': 2},
  {u'source': 42, u'target': 24, u'value': 1},
  {u'source': 43, u'target': 11, u'value': 3},
  {u'source': 43, u'target': 26, u'value': 1},
  {u'source': 43, u'target': 27, u'value': 1},
  {u'source': 44, u'target': 28, u'value': 3},
  {u'source': 44, u'target': 11, u'value': 1},
  {u'source': 45, u'target': 28, u'value': 2},
  {u'source': 47, u'target': 46, u'value': 1},
  {u'source': 48, u'target': 47, u'value': 2},
  {u'source': 48, u'target': 25, u'value': 1},
  {u'source': 48, u'target': 27, u'value': 1},
  {u'source': 48, u'target': 11, u'value': 1},
  {u'source': 49, u'target': 26, u'value': 3},
  {u'source': 49, u'target': 11, u'value': 2},
  {u'source': 50, u'target': 49, u'value': 1},
  {u'source': 50, u'target': 24, u'value': 1},
  {u'source': 51, u'target': 49, u'value': 9},
  {u'source': 51, u'target': 26, u'value': 2},
  {u'source': 51, u'target': 11, u'value': 2},
  {u'source': 52, u'target': 51, u'value': 1},
  {u'source': 52, u'target': 39, u'value': 1},
  {u'source': 53, u'target': 51, u'value': 1},
  {u'source': 54, u'target': 51, u'value': 2},
  {u'source': 54, u'target': 49, u'value': 1},
  {u'source': 54, u'target': 26, u'value': 1},
  {u'source': 55, u'target': 51, u'value': 6},
  {u'source': 55, u'target': 49, u'value': 12},
  {u'source': 55, u'target': 39, u'value': 1},
  {u'source': 55, u'target': 54, u'value': 1},
  {u'source': 55, u'target': 26, u'value': 21},
  {u'source': 55, u'target': 11, u'value': 19},
  {u'source': 55, u'target': 16, u'value': 1},
  {u'source': 55, u'target': 25, u'value': 2},
  {u'source': 55, u'target': 41, u'value': 5},
  {u'source': 55, u'target': 48, u'value': 4},
  {u'source': 56, u'target': 49, u'value': 1},
  {u'source': 56, u'target': 55, u'value': 1},
  {u'source': 57, u'target': 55, u'value': 1},
  {u'source': 57, u'target': 41, u'value': 1},
  {u'source': 57, u'target': 48, u'value': 1},
  {u'source': 58, u'target': 55, u'value': 7},
  {u'source': 58, u'target': 48, u'value': 7},
  {u'source': 58, u'target': 27, u'value': 6},
  {u'source': 58, u'target': 57, u'value': 1},
  {u'source': 58, u'target': 11, u'value': 4},
  {u'source': 59, u'target': 58, u'value': 15},
  {u'source': 59, u'target': 55, u'value': 5},
  {u'source': 59, u'target': 48, u'value': 6},
  {u'source': 59, u'target': 57, u'value': 2},
  {u'source': 60, u'target': 48, u'value': 1},
  {u'source': 60, u'target': 58, u'value': 4},
  {u'source': 60, u'target': 59, u'value': 2},
  {u'source': 61, u'target': 48, u'value': 2},
  {u'source': 61, u'target': 58, u'value': 6},
  {u'source': 61, u'target': 60, u'value': 2},
  {u'source': 61, u'target': 59, u'value': 5},
  {u'source': 61, u'target': 57, u'value': 1},
  {u'source': 61, u'target': 55, u'value': 1},
  {u'source': 62, u'target': 55, u'value': 9},
  {u'source': 62, u'target': 58, u'value': 17},
  {u'source': 62, u'target': 59, u'value': 13},
  {u'source': 62, u'target': 48, u'value': 7},
  {u'source': 62, u'target': 57, u'value': 2},
  {u'source': 62, u'target': 41, u'value': 1},
  {u'source': 62, u'target': 61, u'value': 6},
  {u'source': 62, u'target': 60, u'value': 3},
  {u'source': 63, u'target': 59, u'value': 5},
  {u'source': 63, u'target': 48, u'value': 5},
  {u'source': 63, u'target': 62, u'value': 6},
  {u'source': 63, u'target': 57, u'value': 2},
  {u'source': 63, u'target': 58, u'value': 4},
  {u'source': 63, u'target': 61, u'value': 3},
  {u'source': 63, u'target': 60, u'value': 2},
  {u'source': 63, u'target': 55, u'value': 1},
  {u'source': 64, u'target': 55, u'value': 5},
  {u'source': 64, u'target': 62, u'value': 12},
  {u'source': 64, u'target': 48, u'value': 5},
  {u'source': 64, u'target': 63, u'value': 4},
  {u'source': 64, u'target': 58, u'value': 10},
  {u'source': 64, u'target': 61, u'value': 6},
  {u'source': 64, u'target': 60, u'value': 2},
  {u'source': 64, u'target': 59, u'value': 9},
  {u'source': 64, u'target': 57, u'value': 1},
  {u'source': 64, u'target': 11, u'value': 1},
  {u'source': 65, u'target': 63, u'value': 5},
  {u'source': 65, u'target': 64, u'value': 7},
  {u'source': 65, u'target': 48, u'value': 3},
  {u'source': 65, u'target': 62, u'value': 5},
  {u'source': 65, u'target': 58, u'value': 5},
  {u'source': 65, u'target': 61, u'value': 5},
  {u'source': 65, u'target': 60, u'value': 2},
  {u'source': 65, u'target': 59, u'value': 5},
  {u'source': 65, u'target': 57, u'value': 1},
  {u'source': 65, u'target': 55, u'value': 2},
  {u'source': 66, u'target': 64, u'value': 3},
  {u'source': 66, u'target': 58, u'value': 3},
  {u'source': 66, u'target': 59, u'value': 1},
  {u'source': 66, u'target': 62, u'value': 2},
  {u'source': 66, u'target': 65, u'value': 2},
  {u'source': 66, u'target': 48, u'value': 1},
  {u'source': 66, u'target': 63, u'value': 1},
  {u'source': 66, u'target': 61, u'value': 1},
  {u'source': 66, u'target': 60, u'value': 1},
  {u'source': 67, u'target': 57, u'value': 3},
  {u'source': 68, u'target': 25, u'value': 5},
  {u'source': 68, u'target': 11, u'value': 1},
  {u'source': 68, u'target': 24, u'value': 1},
  {u'source': 68, u'target': 27, u'value': 1},
  {u'source': 68, u'target': 48, u'value': 1},
  {u'source': 68, u'target': 41, u'value': 1},
  {u'source': 69, u'target': 25, u'value': 6},
  {u'source': 69, u'target': 68, u'value': 6},
  {u'source': 69, u'target': 11, u'value': 1},
  {u'source': 69, u'target': 24, u'value': 1},
  {u'source': 69, u'target': 27, u'value': 2},
  {u'source': 69, u'target': 48, u'value': 1},
  {u'source': 69, u'target': 41, u'value': 1},
  {u'source': 70, u'target': 25, u'value': 4},
  {u'source': 70, u'target': 69, u'value': 4},
  {u'source': 70, u'target': 68, u'value': 4},
  {u'source': 70, u'target': 11, u'value': 1},
  {u'source': 70, u'target': 24, u'value': 1},
  {u'source': 70, u'target': 27, u'value': 1},
  {u'source': 70, u'target': 41, u'value': 1},
  {u'source': 70, u'target': 58, u'value': 1},
  {u'source': 71, u'target': 27, u'value': 1},
  {u'source': 71, u'target': 69, u'value': 2},
  {u'source': 71, u'target': 68, u'value': 2},
  {u'source': 71, u'target': 70, u'value': 2},
  {u'source': 71, u'target': 11, u'value': 1},
  {u'source': 71, u'target': 48, u'value': 1},
  {u'source': 71, u'target': 41, u'value': 1},
  {u'source': 71, u'target': 25, u'value': 1},
  {u'source': 72, u'target': 26, u'value': 2},
  {u'source': 72, u'target': 27, u'value': 1},
  {u'source': 72, u'target': 11, u'value': 1},
  {u'source': 73, u'target': 48, u'value': 2},
  {u'source': 74, u'target': 48, u'value': 2},
  {u'source': 74, u'target': 73, u'value': 3},
  {u'source': 75, u'target': 69, u'value': 3},
  {u'source': 75, u'target': 68, u'value': 3},
  {u'source': 75, u'target': 25, u'value': 3},
  {u'source': 75, u'target': 48, u'value': 1},
  {u'source': 75, u'target': 41, u'value': 1},
  {u'source': 75, u'target': 70, u'value': 1},
  {u'source': 75, u'target': 71, u'value': 1},
  # {u'source': 76, u'target': 64, u'value': 1},
  # {u'source': 76, u'target': 65, u'value': 1},
  # {u'source': 76, u'target': 66, u'value': 1},
  # {u'source': 76, u'target': 63, u'value': 1},
  # {u'source': 76, u'target': 62, u'value': 1},
  # {u'source': 76, u'target': 48, u'value': 1},
  # {u'source': 76, u'target': 58, u'value': 1}
    ],
 u'nodes': [{u'group': 1, u'name': u'Myriel', 'something': 'else'},
  {u'group': 1, u'name': u'Napoleon'},
  {u'group': 1, u'name': u'Mlle.Baptistine'},
  {u'group': 1, u'name': u'Mme.Magloire'},
  {u'group': 1, u'name': u'CountessdeLo'},
  {u'group': 1, u'name': u'Geborand'},
  {u'group': 1, u'name': u'Champtercier'},
  {u'group': 1, u'name': u'Cravatte'},
  {u'group': 1, u'name': u'Count'},
  {u'group': 1, u'name': u'OldMan'},
  {u'group': 2, u'name': u'Labarre'},
  {u'group': 2, u'name': u'Valjean'},
  {u'group': 3, u'name': u'Marguerite'},
  {u'group': 2, u'name': u'Mme.deR'},
  {u'group': 2, u'name': u'Isabeau'},
  {u'group': 2, u'name': u'Gervais'},
  {u'group': 3, u'name': u'Tholomyes'},
  {u'group': 3, u'name': u'Listolier'},
  {u'group': 3, u'name': u'Fameuil'},
  {u'group': 3, u'name': u'Blacheville'},
  {u'group': 3, u'name': u'Favourite'},
  {u'group': 3, u'name': u'Dahlia'},
  {u'group': 3, u'name': u'Zephine'},
  {u'group': 3, u'name': u'Fantine'},
  {u'group': 4, u'name': u'Mme.Thenardier'},
  {u'group': 4, u'name': u'Thenardier'},
  {u'group': 5, u'name': u'Cosette'},
  {u'group': 4, u'name': u'Javert'},
  {u'group': 0, u'name': u'Fauchelevent'},
  {u'group': 2, u'name': u'Bamatabois'},
  {u'group': 3, u'name': u'Perpetue'},
  {u'group': 2, u'name': u'Simplice'},
  {u'group': 2, u'name': u'Scaufflaire'},
  {u'group': 2, u'name': u'Woman1'},
  {u'group': 2, u'name': u'Judge'},
  {u'group': 2, u'name': u'Champmathieu'},
  {u'group': 2, u'name': u'Brevet'},
  {u'group': 2, u'name': u'Chenildieu'},
  {u'group': 2, u'name': u'Cochepaille'},
  {u'group': 4, u'name': u'Pontmercy'},
  {u'group': 6, u'name': u'Boulatruelle'},
  {u'group': 4, u'name': u'Eponine'},
  {u'group': 4, u'name': u'Anzelma'},
  {u'group': 5, u'name': u'Woman2'},
  {u'group': 0, u'name': u'MotherInnocent'},
  {u'group': 0, u'name': u'Gribier'},
  {u'group': 7, u'name': u'Jondrette'},
  {u'group': 7, u'name': u'Mme.Burgon'},
  {u'group': 8, u'name': u'Gavroche'},
  {u'group': 5, u'name': u'Gillenormand'},
  {u'group': 5, u'name': u'Magnon'},
  {u'group': 5, u'name': u'Mlle.Gillenormand'},
  {u'group': 5, u'name': u'Mme.Pontmercy'},
  {u'group': 5, u'name': u'Mlle.Vaubois'},
  {u'group': 5, u'name': u'Lt.Gillenormand'},
  {u'group': 8, u'name': u'Marius'},
  {u'group': 5, u'name': u'BaronessT'},
  {u'group': 8, u'name': u'Mabeuf'},
  {u'group': 8, u'name': u'Enjolras'},
  {u'group': 8, u'name': u'Combeferre'},
  {u'group': 8, u'name': u'Prouvaire'},
  {u'group': 8, u'name': u'Feuilly'},
  {u'group': 8, u'name': u'Courfeyrac'},
  {u'group': 8, u'name': u'Bahorel'},
  {u'group': 8, u'name': u'Bossuet'},
  {u'group': 8, u'name': u'Joly'},
  {u'group': 8, u'name': u'Grantaire'},
  {u'group': 9, u'name': u'MotherPlutarch'},
  {u'group': 4, u'name': u'Gueulemer'},
  {u'group': 4, u'name': u'Babet'},
  {u'group': 4, u'name': u'Claquesous'},
  {u'group': 4, u'name': u'Montparnasse'},
  {u'group': 5, u'name': u'Toussaint'},
  {u'group': 10, u'name': u'Child1'},
  {u'group': 10, u'name': u'Child2'},
  {u'group': 4, u'name': u'Brujon'},
  {u'group': 8, u'name': u'Mme.Hucheloup'}]}

    # with open('/Users/maxvitek/Workspaces/coint_site/coint/static/miserables.json', 'r') as f:
    #     sample = json.load(f)

    pair_data = get_pair('AAPL', 'GOOG')
    logger.info('Got pair data.')
    return render(request, template_name='home.html', dictionary={
        'data': pair_data, 'ticker1': 'AAPL', 'ticker2': 'GOOG', 'nodes': json.dumps(sample)})


sample = {u'links': [{u'source': 1, u'target': 0, u'value': 1},
  {u'source': 2, u'target': 0, u'value': 8},
  {u'source': 3, u'target': 0, u'value': 10},
  {u'source': 3, u'target': 2, u'value': 6},
  {u'source': 4, u'target': 0, u'value': 1},
  {u'source': 5, u'target': 0, u'value': 1},
  {u'source': 6, u'target': 0, u'value': 1},
  {u'source': 7, u'target': 0, u'value': 1},
  {u'source': 8, u'target': 0, u'value': 2},
  {u'source': 9, u'target': 0, u'value': 1},
  {u'source': 11, u'target': 10, u'value': 1},
  {u'source': 11, u'target': 3, u'value': 3},
  {u'source': 11, u'target': 2, u'value': 3},
  {u'source': 11, u'target': 0, u'value': 5},
  {u'source': 12, u'target': 11, u'value': 1},
  {u'source': 13, u'target': 11, u'value': 1},
  {u'source': 14, u'target': 11, u'value': 1},
  {u'source': 15, u'target': 11, u'value': 1},
  {u'source': 17, u'target': 16, u'value': 4},
  {u'source': 18, u'target': 16, u'value': 4},
  {u'source': 18, u'target': 17, u'value': 4},
  {u'source': 19, u'target': 16, u'value': 4},
  {u'source': 19, u'target': 17, u'value': 4},
  {u'source': 19, u'target': 18, u'value': 4},
  {u'source': 20, u'target': 16, u'value': 3},
  {u'source': 20, u'target': 17, u'value': 3},
  {u'source': 20, u'target': 18, u'value': 3},
  {u'source': 20, u'target': 19, u'value': 4},
  {u'source': 21, u'target': 16, u'value': 3},
  {u'source': 21, u'target': 17, u'value': 3},
  {u'source': 21, u'target': 18, u'value': 3},
  {u'source': 21, u'target': 19, u'value': 3},
  {u'source': 21, u'target': 20, u'value': 5},
  {u'source': 22, u'target': 16, u'value': 3},
  {u'source': 22, u'target': 17, u'value': 3},
  {u'source': 22, u'target': 18, u'value': 3},
  {u'source': 22, u'target': 19, u'value': 3},
  {u'source': 22, u'target': 20, u'value': 4},
  {u'source': 22, u'target': 21, u'value': 4},
  {u'source': 23, u'target': 16, u'value': 3},
  {u'source': 23, u'target': 17, u'value': 3},
  {u'source': 23, u'target': 18, u'value': 3},
  {u'source': 23, u'target': 19, u'value': 3},
  {u'source': 23, u'target': 20, u'value': 4},
  {u'source': 23, u'target': 21, u'value': 4},
  {u'source': 23, u'target': 22, u'value': 4},
  {u'source': 23, u'target': 12, u'value': 2},
  {u'source': 23, u'target': 11, u'value': 9},
  {u'source': 24, u'target': 23, u'value': 2},
  {u'source': 24, u'target': 11, u'value': 7},
  {u'source': 25, u'target': 24, u'value': 13},
  {u'source': 25, u'target': 23, u'value': 1},
  {u'source': 25, u'target': 11, u'value': 12},
  {u'source': 26, u'target': 24, u'value': 4},
  {u'source': 26, u'target': 11, u'value': 31},
  {u'source': 26, u'target': 16, u'value': 1},
  {u'source': 26, u'target': 25, u'value': 1},
  {u'source': 27, u'target': 11, u'value': 17},
  {u'source': 27, u'target': 23, u'value': 5},
  {u'source': 27, u'target': 25, u'value': 5},
  {u'source': 27, u'target': 24, u'value': 1},
  {u'source': 27, u'target': 26, u'value': 1},
  {u'source': 28, u'target': 11, u'value': 8},
  {u'source': 28, u'target': 27, u'value': 1},
  {u'source': 29, u'target': 23, u'value': 1},
  {u'source': 29, u'target': 27, u'value': 1},
  {u'source': 29, u'target': 11, u'value': 2},
  {u'source': 30, u'target': 23, u'value': 1},
  {u'source': 31, u'target': 30, u'value': 2},
  {u'source': 31, u'target': 11, u'value': 3},
  {u'source': 31, u'target': 23, u'value': 2},
  {u'source': 31, u'target': 27, u'value': 1},
  {u'source': 32, u'target': 11, u'value': 1},
  {u'source': 33, u'target': 11, u'value': 2},
  {u'source': 33, u'target': 27, u'value': 1},
  {u'source': 34, u'target': 11, u'value': 3},
  {u'source': 34, u'target': 29, u'value': 2},
  {u'source': 35, u'target': 11, u'value': 3},
  {u'source': 35, u'target': 34, u'value': 3},
  {u'source': 35, u'target': 29, u'value': 2},
  {u'source': 36, u'target': 34, u'value': 2},
  {u'source': 36, u'target': 35, u'value': 2},
  {u'source': 36, u'target': 11, u'value': 2},
  {u'source': 36, u'target': 29, u'value': 1},
  {u'source': 37, u'target': 34, u'value': 2},
  {u'source': 37, u'target': 35, u'value': 2},
  {u'source': 37, u'target': 36, u'value': 2},
  {u'source': 37, u'target': 11, u'value': 2},
  {u'source': 37, u'target': 29, u'value': 1},
  {u'source': 38, u'target': 34, u'value': 2},
  {u'source': 38, u'target': 35, u'value': 2},
  {u'source': 38, u'target': 36, u'value': 2},
  {u'source': 38, u'target': 37, u'value': 2},
  {u'source': 38, u'target': 11, u'value': 2},
  {u'source': 38, u'target': 29, u'value': 1},
  {u'source': 39, u'target': 25, u'value': 1},
  {u'source': 40, u'target': 25, u'value': 1},
  {u'source': 41, u'target': 24, u'value': 2},
  {u'source': 41, u'target': 25, u'value': 3},
  {u'source': 42, u'target': 41, u'value': 2},
  {u'source': 42, u'target': 25, u'value': 2},
  {u'source': 42, u'target': 24, u'value': 1},
  {u'source': 43, u'target': 11, u'value': 3},
  {u'source': 43, u'target': 26, u'value': 1},
  {u'source': 43, u'target': 27, u'value': 1},
  {u'source': 44, u'target': 28, u'value': 3},
  {u'source': 44, u'target': 11, u'value': 1},
  {u'source': 45, u'target': 28, u'value': 2},
  {u'source': 47, u'target': 46, u'value': 1},
  {u'source': 48, u'target': 47, u'value': 2},
  {u'source': 48, u'target': 25, u'value': 1},
  {u'source': 48, u'target': 27, u'value': 1},
  {u'source': 48, u'target': 11, u'value': 1},
  {u'source': 49, u'target': 26, u'value': 3},
  {u'source': 49, u'target': 11, u'value': 2},
  {u'source': 50, u'target': 49, u'value': 1},
  {u'source': 50, u'target': 24, u'value': 1},
  {u'source': 51, u'target': 49, u'value': 9},
  {u'source': 51, u'target': 26, u'value': 2},
  {u'source': 51, u'target': 11, u'value': 2},
  {u'source': 52, u'target': 51, u'value': 1},
  {u'source': 52, u'target': 39, u'value': 1},
  {u'source': 53, u'target': 51, u'value': 1},
  {u'source': 54, u'target': 51, u'value': 2},
  {u'source': 54, u'target': 49, u'value': 1},
  {u'source': 54, u'target': 26, u'value': 1},
  {u'source': 55, u'target': 51, u'value': 6},
  {u'source': 55, u'target': 49, u'value': 12},
  {u'source': 55, u'target': 39, u'value': 1},
  {u'source': 55, u'target': 54, u'value': 1},
  {u'source': 55, u'target': 26, u'value': 21},
  {u'source': 55, u'target': 11, u'value': 19},
  {u'source': 55, u'target': 16, u'value': 1},
  {u'source': 55, u'target': 25, u'value': 2},
  {u'source': 55, u'target': 41, u'value': 5},
  {u'source': 55, u'target': 48, u'value': 4},
  {u'source': 56, u'target': 49, u'value': 1},
  {u'source': 56, u'target': 55, u'value': 1},
  {u'source': 57, u'target': 55, u'value': 1},
  {u'source': 57, u'target': 41, u'value': 1},
  {u'source': 57, u'target': 48, u'value': 1},
  {u'source': 58, u'target': 55, u'value': 7},
  {u'source': 58, u'target': 48, u'value': 7},
  {u'source': 58, u'target': 27, u'value': 6},
  {u'source': 58, u'target': 57, u'value': 1},
  {u'source': 58, u'target': 11, u'value': 4},
  {u'source': 59, u'target': 58, u'value': 15},
  {u'source': 59, u'target': 55, u'value': 5},
  {u'source': 59, u'target': 48, u'value': 6},
  {u'source': 59, u'target': 57, u'value': 2},
  {u'source': 60, u'target': 48, u'value': 1},
  {u'source': 60, u'target': 58, u'value': 4},
  {u'source': 60, u'target': 59, u'value': 2},
  {u'source': 61, u'target': 48, u'value': 2},
  {u'source': 61, u'target': 58, u'value': 6},
  {u'source': 61, u'target': 60, u'value': 2},
  {u'source': 61, u'target': 59, u'value': 5},
  {u'source': 61, u'target': 57, u'value': 1},
  {u'source': 61, u'target': 55, u'value': 1},
  {u'source': 62, u'target': 55, u'value': 9},
  {u'source': 62, u'target': 58, u'value': 17},
  {u'source': 62, u'target': 59, u'value': 13},
  {u'source': 62, u'target': 48, u'value': 7},
  {u'source': 62, u'target': 57, u'value': 2},
  {u'source': 62, u'target': 41, u'value': 1},
  {u'source': 62, u'target': 61, u'value': 6},
  {u'source': 62, u'target': 60, u'value': 3},
  {u'source': 63, u'target': 59, u'value': 5},
  {u'source': 63, u'target': 48, u'value': 5},
  {u'source': 63, u'target': 62, u'value': 6},
  {u'source': 63, u'target': 57, u'value': 2},
  {u'source': 63, u'target': 58, u'value': 4},
  {u'source': 63, u'target': 61, u'value': 3},
  {u'source': 63, u'target': 60, u'value': 2},
  {u'source': 63, u'target': 55, u'value': 1},
  {u'source': 64, u'target': 55, u'value': 5},
  {u'source': 64, u'target': 62, u'value': 12},
  {u'source': 64, u'target': 48, u'value': 5},
  {u'source': 64, u'target': 63, u'value': 4},
  {u'source': 64, u'target': 58, u'value': 10},
  {u'source': 64, u'target': 61, u'value': 6},
  {u'source': 64, u'target': 60, u'value': 2},
  {u'source': 64, u'target': 59, u'value': 9},
  {u'source': 64, u'target': 57, u'value': 1},
  {u'source': 64, u'target': 11, u'value': 1},
  {u'source': 65, u'target': 63, u'value': 5},
  {u'source': 65, u'target': 64, u'value': 7},
  {u'source': 65, u'target': 48, u'value': 3},
  {u'source': 65, u'target': 62, u'value': 5},
  {u'source': 65, u'target': 58, u'value': 5},
  {u'source': 65, u'target': 61, u'value': 5},
  {u'source': 65, u'target': 60, u'value': 2},
  {u'source': 65, u'target': 59, u'value': 5},
  {u'source': 65, u'target': 57, u'value': 1},
  {u'source': 65, u'target': 55, u'value': 2},
  {u'source': 66, u'target': 64, u'value': 3},
  {u'source': 66, u'target': 58, u'value': 3},
  {u'source': 66, u'target': 59, u'value': 1},
  {u'source': 66, u'target': 62, u'value': 2},
  {u'source': 66, u'target': 65, u'value': 2},
  {u'source': 66, u'target': 48, u'value': 1},
  {u'source': 66, u'target': 63, u'value': 1},
  {u'source': 66, u'target': 61, u'value': 1},
  {u'source': 66, u'target': 60, u'value': 1},
  {u'source': 67, u'target': 57, u'value': 3},
  {u'source': 68, u'target': 25, u'value': 5},
  {u'source': 68, u'target': 11, u'value': 1},
  {u'source': 68, u'target': 24, u'value': 1},
  {u'source': 68, u'target': 27, u'value': 1},
  {u'source': 68, u'target': 48, u'value': 1},
  {u'source': 68, u'target': 41, u'value': 1},
  {u'source': 69, u'target': 25, u'value': 6},
  {u'source': 69, u'target': 68, u'value': 6},
  {u'source': 69, u'target': 11, u'value': 1},
  {u'source': 69, u'target': 24, u'value': 1},
  {u'source': 69, u'target': 27, u'value': 2},
  {u'source': 69, u'target': 48, u'value': 1},
  {u'source': 69, u'target': 41, u'value': 1},
  {u'source': 70, u'target': 25, u'value': 4},
  {u'source': 70, u'target': 69, u'value': 4},
  {u'source': 70, u'target': 68, u'value': 4},
  {u'source': 70, u'target': 11, u'value': 1},
  {u'source': 70, u'target': 24, u'value': 1},
  {u'source': 70, u'target': 27, u'value': 1},
  {u'source': 70, u'target': 41, u'value': 1},
  {u'source': 70, u'target': 58, u'value': 1},
  {u'source': 71, u'target': 27, u'value': 1},
  {u'source': 71, u'target': 69, u'value': 2},
  {u'source': 71, u'target': 68, u'value': 2},
  {u'source': 71, u'target': 70, u'value': 2},
  {u'source': 71, u'target': 11, u'value': 1},
  {u'source': 71, u'target': 48, u'value': 1},
  {u'source': 71, u'target': 41, u'value': 1},
  {u'source': 71, u'target': 25, u'value': 1},
  {u'source': 72, u'target': 26, u'value': 2},
  {u'source': 72, u'target': 27, u'value': 1},
  {u'source': 72, u'target': 11, u'value': 1},
  {u'source': 73, u'target': 48, u'value': 2},
  {u'source': 74, u'target': 48, u'value': 2},
  {u'source': 74, u'target': 73, u'value': 3},
  {u'source': 75, u'target': 69, u'value': 3},
  {u'source': 75, u'target': 68, u'value': 3},
  {u'source': 75, u'target': 25, u'value': 3},
  {u'source': 75, u'target': 48, u'value': 1},
  {u'source': 75, u'target': 41, u'value': 1},
  {u'source': 75, u'target': 70, u'value': 1},
  {u'source': 75, u'target': 71, u'value': 1},
  {u'source': 76, u'target': 64, u'value': 1},
  {u'source': 76, u'target': 65, u'value': 1},
  {u'source': 76, u'target': 66, u'value': 1},
  {u'source': 76, u'target': 63, u'value': 1},
  {u'source': 76, u'target': 62, u'value': 1},
  {u'source': 76, u'target': 48, u'value': 1},
  {u'source': 76, u'target': 58, u'value': 1}],
 u'nodes': [{u'group': 1, u'name': u'Myriel', 'something': 'else'},
  {u'group': 1, u'name': u'Napoleon'},
  {u'group': 1, u'name': u'Mlle.Baptistine'},
  {u'group': 1, u'name': u'Mme.Magloire'},
  {u'group': 1, u'name': u'CountessdeLo'},
  {u'group': 1, u'name': u'Geborand'},
  {u'group': 1, u'name': u'Champtercier'},
  {u'group': 1, u'name': u'Cravatte'},
  {u'group': 1, u'name': u'Count'},
  {u'group': 1, u'name': u'OldMan'},
  {u'group': 2, u'name': u'Labarre'},
  {u'group': 2, u'name': u'Valjean'},
  {u'group': 3, u'name': u'Marguerite'},
  {u'group': 2, u'name': u'Mme.deR'},
  {u'group': 2, u'name': u'Isabeau'},
  {u'group': 2, u'name': u'Gervais'},
  {u'group': 3, u'name': u'Tholomyes'},
  {u'group': 3, u'name': u'Listolier'},
  {u'group': 3, u'name': u'Fameuil'},
  {u'group': 3, u'name': u'Blacheville'},
  {u'group': 3, u'name': u'Favourite'},
  {u'group': 3, u'name': u'Dahlia'},
  {u'group': 3, u'name': u'Zephine'},
  {u'group': 3, u'name': u'Fantine'},
  {u'group': 4, u'name': u'Mme.Thenardier'},
  {u'group': 4, u'name': u'Thenardier'},
  {u'group': 5, u'name': u'Cosette'},
  {u'group': 4, u'name': u'Javert'},
  {u'group': 0, u'name': u'Fauchelevent'},
  {u'group': 2, u'name': u'Bamatabois'},
  {u'group': 3, u'name': u'Perpetue'},
  {u'group': 2, u'name': u'Simplice'},
  {u'group': 2, u'name': u'Scaufflaire'},
  {u'group': 2, u'name': u'Woman1'},
  {u'group': 2, u'name': u'Judge'},
  {u'group': 2, u'name': u'Champmathieu'},
  {u'group': 2, u'name': u'Brevet'},
  {u'group': 2, u'name': u'Chenildieu'},
  {u'group': 2, u'name': u'Cochepaille'},
  {u'group': 4, u'name': u'Pontmercy'},
  {u'group': 6, u'name': u'Boulatruelle'},
  {u'group': 4, u'name': u'Eponine'},
  {u'group': 4, u'name': u'Anzelma'},
  {u'group': 5, u'name': u'Woman2'},
  {u'group': 0, u'name': u'MotherInnocent'},
  {u'group': 0, u'name': u'Gribier'},
  {u'group': 7, u'name': u'Jondrette'},
  {u'group': 7, u'name': u'Mme.Burgon'},
  {u'group': 8, u'name': u'Gavroche'},
  {u'group': 5, u'name': u'Gillenormand'},
  {u'group': 5, u'name': u'Magnon'},
  {u'group': 5, u'name': u'Mlle.Gillenormand'},
  {u'group': 5, u'name': u'Mme.Pontmercy'},
  {u'group': 5, u'name': u'Mlle.Vaubois'},
  {u'group': 5, u'name': u'Lt.Gillenormand'},
  {u'group': 8, u'name': u'Marius'},
  {u'group': 5, u'name': u'BaronessT'},
  {u'group': 8, u'name': u'Mabeuf'},
  {u'group': 8, u'name': u'Enjolras'},
  {u'group': 8, u'name': u'Combeferre'},
  {u'group': 8, u'name': u'Prouvaire'},
  {u'group': 8, u'name': u'Feuilly'},
  {u'group': 8, u'name': u'Courfeyrac'},
  {u'group': 8, u'name': u'Bahorel'},
  {u'group': 8, u'name': u'Bossuet'},
  {u'group': 8, u'name': u'Joly'},
  {u'group': 8, u'name': u'Grantaire'},
  {u'group': 9, u'name': u'MotherPlutarch'},
  {u'group': 4, u'name': u'Gueulemer'},
  {u'group': 4, u'name': u'Babet'},
  {u'group': 4, u'name': u'Claquesous'},
  {u'group': 4, u'name': u'Montparnasse'},
  {u'group': 5, u'name': u'Toussaint'},
  {u'group': 10, u'name': u'Child1'},
  {u'group': 10, u'name': u'Child2'},
  {u'group': 4, u'name': u'Brujon'},
  {u'group': 8, u'name': u'Mme.Hucheloup'}]}